GIVE1004/Front

package-lock.json
package.json
src/components/Boxes/CheckBoxes.js
src/components/Boxes/SelectBoxes.js
src/components/Buttons/RadioButtons.js
src/components/Colors/colors.js
src/screens/MainBottomTabs/SearchScreen.js
yarn.lock

**개요**
- feat: init Component
**타입**
** 작업 내용**
- 기본 컴포넌트 구성 완료
- 그래프 제작 중

feat: init Component

---

src/screens/MainBottomTabs/ChartScreen.js
src/screens/MainBottomTabs/MainScreen.js
src/screens/MainBottomTabs/SearchScreen.js
src/screens/MainBottomTabs/StarScreen.js
src/screens/MainBottomTabs/UserScreen.js

**개요**
- fix: keyBoard 에러
**타입**
** 작업 내용**
- input 박스 켜져있을 때 keyboard 내려오지 않는 문제 해결책 제시

fix: textinput 시 키보드 문제 확인

---

package-lock.json
package.json
src/components/Graphs/Graphs.js
src/components/Typography/Spacer.js

**개요**
- feat: Graph 및 Spacer 컴포넌트화 완료
**타입**
** 작업 내용**
- Graph 및 Spacer 컴포넌트화 완료

feat: Graph 및 Spacer 컴포넌트화 완료

---

src/components/footers/footers.js
src/screens/MainBottomTabs/MainScreen.js

feat: footer component & modal 작업 중

feat: footer component & modal 작업 중

---

src/components/footers/footers.js
src/components/modals/modals.js
src/screens/GroupDetailScreen/GroupDetailScreen.js
src/screens/MainBottomTabs/MainScreen.js

feat: modal 및 footer Component 완료

feat: modal 및 footer Component 완료

---

package-lock.json
package.json
src/components/Graphs/Graphs.js
src/components/Headers/Headers.js
src/components/Icons/IconName.js
src/components/Inputs/Inputs.js
src/components/footers/footers.js
src/components/modals/modals.js
src/modules/mainModule/mainCard.js
src/screens/GroupDetailScreen/GroupDetailScreen.js
src/screens/MainBottomTabs/MainScreen.js

feat: mainGraphCard 완료 및 라벨 작업 중

feat: mainGraphCard 완료 및 라벨 작업 중

---

src/components/Images/ImageLoader.js
src/components/Labels/Labels.js
src/modules/mainModule/MainCard.js
src/screens/MainBottomTabs/MainScreen.js

**개요**
- fix: label 스크롤 수정
**타입**
** 작업 내용**
- label 스크롤 수정

fix: label 스크롤 수정

---

src/components/Graphs/Graphs.js
src/components/Images/ImageLoader.js
src/modules/mainModule/MainCard.js
src/screens/GroupDetailScreen/GroupDetailScreen.js
src/screens/MainBottomTabs/MainScreen.js

**개요**
- feat: MainScreen UI 완료
**타입**
** 작업 내용**
- MainScreen UI 완료

feat: MainScreen UI 완료

---

src/modules/serchModule/SearchCard.js
src/screens/MainBottomTabs/SearchScreen.js
src/util/util.js

feat: Scaleing

---

ios/Podfile.lock
package-lock.json
package.json
src/components/Sliders/Sliders.js
src/screens/GroupDetailScreen/GroupDetailScreen.js

**개요**
- feat: Slider Componet 완료
**타입**
** 작업 내용**
- Slider Componet 완료

feat: Slider Componet 완료

---

src/components/Labels/Labels.js
src/components/Typography/Typography.js
src/modules/mainModule/MainCard.js
src/screens/GroupDetailScreen/GroupDetailScreen.js
src/screens/MainBottomTabs/StarScreen.js

**개요**
- feat: Text 공간 넘을 시 ... 처리 및 세부적 사항 추가
**타입**
** 작업 내용**
- Text 공간 넘을 시 ... 처리 및 세부적 사항 추가

feat: Text 공간 넘을 시 ... 처리 및 세부적 사항 추가

---

src/modules/searchModule/SearchCard.js

feat: searchCard

---

package-lock.json
package.json
src/components/ProgressStatus/ProgressStatus.js
src/components/Sliders/Sliders.js
src/modules/groupDetailModule/GroupAIReportCard.js
src/modules/groupDetailModule/GroupBasicCard.js

feat: GroupAIReport UI 완료

---

package-lock.json
package.json
src/modules/groupDetailModule/GroupBasicCard.js
src/modules/groupDetailModule/GroupFinancialCard.js

feat: GroupFinancialCard

---

src/modules/MyHistoryModule/MyHistoryCard.js
src/modules/searchModule/SearchCard.js
src/screens/MainBottomTabs/ChartScreen.js

fix: searchScreen

---

src/navigations/AuthStackNavigation.js
src/navigations/MainBottomTabNavigation.js
src/screens/authScreen/OauthScreen.js
src/screens/authScreen/SplashScreen.js
src/screens/groupDetailScreen/GroupDetailScreen.js
src/screens/mainBottomTabs/ChartScreen.js
src/screens/mainBottomTabs/ChatScreen.js
src/screens/mainBottomTabs/MainScreen.js
src/screens/mainBottomTabs/SearchScreen.js
src/screens/mainBottomTabs/UserScreen.js
src/screens/settingScreen/CalScreen.js
src/screens/settingScreen/PlusScreen.js
src/screens/settingScreen/StarScreen.js
src/screens/settingScreen/UserInfoScreen.js
src/stacks/MainStack.js

chore: 폴더명 변경

---

src/components/Headers/Headers.js
src/navigations/AuthStackNavigation.js
src/screens/AuthScreen/OauthScreen.js
src/screens/authScreen/OauthScreen.js
src/screens/questionScreen/QuestionScreen.js
src/util/recoil/Atoms.js

feat: QuestionScreen 작업 중

---

src/components/Sliders/Sliders.js
src/screens/reviewScreen/ReviewScreen.js

fix: slider 크기 조정

---

package-lock.json
package.json
src/components/Sliders/ViewSliders.js

fix: 의존성 수정 및 ViewSlider 에러 해결

fix: 의존성 수정 및 ViewSlider 에러 해결

---

src/components/Sliders/Sliders.js
src/components/Sliders/ViewSliders.js
src/modules/searchModule/SearchCard.js
src/screens/reviewScreen/ReviewScreen.js

fix:MySlider

---

src/modules/MyHistoryModule/MyHistoryCard.js
src/modules/searchModule/SearchCard.js
src/screens/mainBottomTabs/ChartScreen.js
src/screens/reviewScreen/ReviewScreen.js
src/util/util.js

fix : ChartScreen, ReviewScreen

---

src/screens/authScreen/OauthScreen.js
src/util/fetch/fetchUtil.js

feat: Oauth Fetch Token값 가져오기완료. 분기처리 필요

feat: Oauth Fetch Token값 가져오기완료. 분기처리 필요

---

src/modules/MyHistoryModule/MyHistoryCard.js
src/modules/starModule/StarCardModule.js
src/screens/mainBottomTabs/SearchScreen.js
src/screens/reviewScreen/ReviewScreen.js
src/screens/settingScreen/StarScreen.js
src/stacks/MainStack.js

fix : ReviewScreen, ChartScreen, StarScreen

---

src/components/Buttons/RadioButtons.js
src/screens/groupDetailScreen/GroupDetailScreen.js
src/screens/mainBottomTabs/ChartScreen.js

fix : Donnation

---

src/screens/groupDetailScreen/GroupDetailScreen.js
src/screens/reviewScreen/ReviewScreen.js

fix : ChartScreen

---

ios/Podfile.lock
package-lock.json
package.json
src/screens/authScreen/OauthScreen.js
src/screens/mainBottomTabs/MainScreen.js
src/util/async/asyncUtil.js
src/util/fetch/fetchUtil.js
src/util/recoil/Atoms.js
src/util/token/tokenUtil.js

feat: login로직 작업 중

---

package-lock.json
src/screens/groupDetailScreen/GroupDetailScreen.js
src/screens/mainBottomTabs/ChartScreen.js

fix: GroupDetailScreen, ChartScreen 수정

---

src/components/Footers/Footers.js
src/modules/starModule/StarCardModule.js
src/screens/authScreen/OauthScreen.js
src/screens/authScreen/SplashScreen.js
src/screens/groupDetailScreen/GroupDetailScreen.js
src/screens/mainBottomTabs/ChartScreen.js
src/screens/reviewScreen/ReviewScreen.js
src/screens/settingScreen/StarScreen.js

feat: 세부사항 수정

---

src/modules/groupDetailModule/GroupModalView.js
src/screens/groupDetailScreen/GroupDetailScreen.js
src/screens/reviewScreen/ReviewScreen.js

feat: modal 모듈화(분리)

---

src/components/Buttons/RadioButtons.js
src/modules/groupDetailModule/GroupAIReportModule.js
src/modules/groupDetailModule/GroupModalModule.js
src/modules/reportModule/ReportDonationGroupModule.js
src/modules/reportModule/ReportMyDonationModule.js
src/modules/reportModule/ReportTopTabModule.js
src/screens/authScreen/SplashScreen.js
src/screens/groupDetailScreen/GroupDetailScreen.js
src/screens/questionScreen/QuestionScreen.js

**개요**
- fix: routing 처리 및 질문 페이지 변경 예상도
**타입**
** 작업 내용**

fix: routing 처리 및 질문 페이지 변경 예상도

---

src/modules/groupDetailModule/GroupAIReportModule.js
src/modules/groupDetailModule/GroupNewsModule.js
src/screens/authScreen/OauthScreen.js
src/screens/authScreen/SplashScreen.js
src/screens/questionScreen/QuestionScreen.js
src/util/fetch/fetchUtil.js
src/util/token/tokenUtil.js

**개요**
- fix: token 관련 사항 수정 및 GIVE AI Comment 추가
**타입**
** 작업 내용**
fetchUtil.js 내 accessToken 가져오는 코드 추가
tokenUtil.js 내 accessToken 가져오는 코드 수정
question 시 사용하던 getToken 삭제 및 이동
refreshFetch시 setToken 파트 안 됨 수정
GIVE AI Comment Axios(비동기 통신) 파트 추가

fix: token 관련 사항 수정 및 GIVE AI Comment 추가
